version: '3.9'

services:
  chat-ai:
    image: node:20          # Usa Node.js 20 jรก pronto
    container_name: chat-ai
    working_dir: /app
    volumes:
      - ./app:/app          # mapeia a pasta app para dentro do container
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000

